service:
  name: KracknowExamScheduleService

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    includeModules: 
      packagePath: '../../package.json'

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(../../env/${self:provider.stage}.yml)}
  stage: ${opt:stage, 'dev'}
  profile: kracknow
  region: ap-south-1
  iamRoleStatements: 
    - Effect: 'Allow'
      Action: 
        - 'sns:Publish'
      Resource: 
        - '*'
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:provider.stage}-kracknow-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:provider.stage}-kracknow-ApiGatewayRestApiRootResourceId
  

functions:
  schedule:
    handler: lambda.handler
    events:
      - http:
          path: '/schedules'
          method: 'ANY'
          cors: ${file(../../env/cors.yml)}
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:provider.stage}-kracknow-ApiGatewayAuthorizer
      - http:
          path: '/schedules/{proxy+}'
          method: 'ANY'
          cors: ${file(../../env/cors.yml)}
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:provider.stage}-kracknow-ApiGatewayAuthorizer
