#!/bin/bash
# It generates a serverless service inside services folder with the given name.
if [ $# -eq 0 ]
  then
    echo "Argument missing"
    exit 1
fi

serverless create --template aws-nodejs-typescript --path services/$1 --name $1-service