export const INBOUND = "INBOUND";
export const OUTBOUND = "OUTBOUND";
export const ADMIN = "ADMIN";
export const SUCCESS = "SUCCESS";
export const EARNED_COIN = "EARNED COIN";
export const EARNED_PRIZE = "EARNED PRIZE";
export const EXAM_FEE = "EXAM FEE";
export const WALLET = "WALLET";
export const ONLY_ADMIN_ALLOWED = "ONLY ADMIN ALLOWED";
export const PENDING = "PENDING";
export const COMPLETED = "COMPLETED";
export const APPEARED = 'APPEARED'
export const ACCEPTED = "ACCEPTED";
export const INITIALIZED = "INITIALIZED";
export const NEW_STUDENT_INITIAL_AMOUNT = "new_student_initial_amount";
export const NEW_WITHDRWAL_LIMIT = "new_withdrawal_limit"
export const PUBLIC_KEY = "public_key";
export const STUDENT_RELOGIN = "Please Login Once";

export const EXAM_IS_COMPLETED =
  "Exam is complete. Please check the leaderboard";
export const FCM = "FCM";
export const ACTIVE = "Active";
export const IN_ACTIVE = "In-Active";
export const ENABLED = "ENABLED";
export const SCHEDULED = "SCHEDULED";
export const TOURNAMENT = "TOURNAMENT";
export const REGISTERED = "REGISTERED";
export const TOURNAMENT_JOIN_AMOUNT = "Tournament join amount"
export const NOT_COMPLETED = "NOT_COMPLETED"
export const NO_PENDING_WITHDRAWAL_FOUND = "No Pending Withdrawal Found"