service:
  name: KracknowCommonService

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(../../env/${self:provider.stage}.yml)}
  stage: ${opt:stage, 'dev'}
  profile: kracknow
  region: ap-south-1
  iamRoleStatements: 
    - Effect: 'Allow'
      Action: 
        - 'sns:Publish'
      Resource: 
        - '*'
    - Effect: "Allow"
      Action:
       - "s3:*"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::kracknow-dev", "/*" ] ] }
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:provider.stage}-kracknow-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:provider.stage}-kracknow-ApiGatewayRestApiRootResourceId
  

functions:
  common:
    handler: lambda.handler
    events:
      - http:
          path: '/common'
          method: 'ANY'
          cors: ${file(../../env/cors.yml)}
      - http:
          path: '/common/{proxy+}'
          method: 'ANY'
          cors: ${file(../../env/cors.yml)}
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:provider.stage}-kracknow-ApiGatewayAuthorizer
