service:
  name: KracknowCashfreeWebhook-Event

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(../../env/${self:provider.stage}.yml)}
  stage: ${opt:stage, 'dev'}
  profile: kracknow
  region: ap-south-1
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:provider.stage}-kracknow-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:provider.stage}-kracknow-ApiGatewayRestApiRootResourceId
  
functions:
  CashfreeWebhook:
    handler: lambda.handler
    events:
      - http:
          path: '/webhook/cashfree'
          method: 'any'
          cors: ${file(../../env/cors.yml)}
